import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { projects } from './catalog.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const evidence = JSON.parse(await readFile(path.join(root, 'assets', 'captured-output.json'), 'utf8'));
const data = { capturedAt: evidence.capturedAt, nodeVersion: evidence.nodeVersion, projects: [] };
for (const project of projects) {
  const location = path.join(root, 'projects', project.folder);
  const names = (await readdir(location)).filter(name => /\.(js|json|md|txt)$/.test(name) && !['notes.txt', 'copy.txt'].includes(name) && !(project.id === 'file-system' && name === 'output.txt'));
  names.sort((a, b) => a === project.entry ? -1 : b === project.entry ? 1 : a.localeCompare(b));
  const files = await Promise.all(names.map(async name => ({ name, source: await readFile(path.join(location, name), 'utf8') })));
  data.projects.push({ ...project, files, outputs: evidence.records[project.id] });
}
await mkdir(path.join(root, 'assets'), { recursive: true });
// Classic JS works on static hosting and when index.html is opened directly.
await writeFile(path.join(root, 'assets', 'projects-data.js'), `// Generated by npm run build from project sources and captured execution.\nwindow.LAB_DATA = ${JSON.stringify(data).replaceAll('<', '\\u003c')};\n`);
console.log(`Built ${data.projects.length} projects with ${data.projects.reduce((n, p) => n + p.files.length, 0)} browsable files.`);
